<?php
function ferrn_shot(string $url): string { return 'https://s.wordpress.com/mshots/v1/'.rawurlencode($url).'?w=1600'; }
$pageTitle='Ferrn Digital Agency — Websites & Web Applications Built for Growth';
$pageDescription='Ferrn Digital Agency builds conversion-focused websites, custom web applications, portals, dashboards and digital systems for ambitious businesses.';
$canonical='https://www.ferrnagency.com/';
$schema=['@context'=>'https://schema.org','@graph'=>[
 ['@type'=>'Organization','@id'=>'https://www.ferrnagency.com/#org','name'=>'Ferrn Digital Agency','url'=>'https://www.ferrnagency.com/','email'=>'info@ferrnagency.com','logo'=>'https://raw.githubusercontent.com/FERRN-AGENCY/ferrn-website/main/fern/src/assets/Fern.svg','description'=>$pageDescription,'areaServed'=>'Worldwide','sameAs'=>['https://www.instagram.com/ferrn.agency/','https://x.com/ferrn_agency','https://www.linkedin.com/company/109135329/','https://www.tiktok.com/@ferrnagency']],
 ['@type'=>'WebSite','@id'=>'https://www.ferrnagency.com/#website','url'=>'https://www.ferrnagency.com/','name'=>'Ferrn Digital Agency','publisher'=>['@id'=>'https://www.ferrnagency.com/#org']],
 ['@type'=>'Service','name'=>'Website design and web application development','provider'=>['@id'=>'https://www.ferrnagency.com/#org'],'areaServed'=>'Worldwide','serviceType'=>['Web Design','Web Development','Custom Web Applications','UI/UX Design','AI Automation']]
]];
$featured=[
 ['relay','Relay — Delivery-to-Cash Control','Freight operations','Web application','https://freight-app1.netlify.app/','A web application designed to surface invoice blockers, revenue recovery opportunities and post-delivery exceptions before they disappear into spreadsheets and inboxes.','Turns revenue states into a visible, actionable workflow.'],
 ['gromzia','Gromzia Ventures','Logistics','Corporate website','https://www.gromzialtd.com/','A clearer digital expression of a long-established logistics business, built to surface service breadth, trust and operating credibility.','Credibility and service range become visible before the first conversation.'],
 ['mpi','M-P Infrastructure','Infrastructure','Corporate website','https://www.mpiafrica.com/','A project-led digital experience that organises a complex EPC business across telecoms, energy, civil works, water, oil & gas and real estate.','Multi-sector capability is easier for institutional buyers to evaluate.'],
 ['synergix','Synergix Africa','Entrepreneurship','Platform website','https://www.synergixafrica.com/','Programs, funding, tools and community support organised into clear journeys for entrepreneurs at different stages of growth.','One ecosystem can support multiple programs without becoming confusing.'],
 ['insightblitz','Insightblitz','Web3 growth','Web3 website','https://insightblitz.io/','A sharper authority and go-to-market story for a Web3 growth partner working across KOL campaigns, distribution, partnerships and launch execution.','Proof, offer and distribution capability work as one sales narrative.'],
 ['wib-fair','WIB Fair 2026','Events','Event website','https://wibfair.ng/','An event site structured around attendance, vendor registration, exhibitor value, sponsors, FAQs and an always-on route to secure a spot.','The website becomes part of event sales, not just event information.']
];
?><!doctype html><html lang="en" data-theme="dark"><head><?php include __DIR__.'/lib/head.php'; ?></head><body>
<?php include __DIR__.'/lib/nav.php'; ?>
<main>
<section class="hero" id="top"><div class="container hero-inner"><div class="hero-topline reveal"><div class="availability"><span class="availability-dot"></span>Taking on selected web & product projects</div></div><h1 class="reveal">We build digital products that make businesses <span class="accent">hard to ignore.</span></h1><div class="hero-bottom reveal"><p class="hero-copy">Ferrn Digital Agency designs and develops websites and web applications that make businesses easier to trust, easier to buy from, and easier to run.</p><div class="hero-actions"><a class="btn btn-primary" href="#contact">Start a project <i data-lucide="arrow-up-right"></i></a><a class="btn btn-ghost" href="/work/">See the work <i data-lucide="arrow-right"></i></a></div></div><div class="hero-proof reveal"><p>Built across websites, platforms and operational systems</p><div class="proof-chips"><span class="proof-chip">Websites</span><span class="proof-chip">Web apps</span><span class="proof-chip">Portals</span><span class="proof-chip">Dashboards</span><span class="proof-chip">AI workflows</span></div></div></div></section>

<section class="client-rail" aria-label="Clients"><div class="marquee"><?php $logos=[['clientLogo1.svg','Gromzia'],['clientLogo2.svg','Synergix Africa'],['clientLogo3.svg','M-P Infrastructure'],['clientLogo4.svg','WIB Fair'],['clientLogo5.svg','Aroda'],['clientLogo6.svg','Outbox Experience'],['clientLogo7.svg','Knomi'],['clientLogo12.svg','Padher']]; foreach(array_merge($logos,$logos) as $l):?><div class="client-logo"><img src="https://raw.githubusercontent.com/FERRN-AGENCY/ferrn-website/main/fern/src/assets/<?=htmlspecialchars($l[0])?>" alt="<?=htmlspecialchars($l[1])?>"></div><?php endforeach;?></div></section>

<section class="section"><div class="container"><div class="section-head reveal"><div><span class="eyebrow">Selected impact</span><h2 class="h2">The interface is visible. The business effect is the point.</h2></div><p class="lead">Every featured project opens into the problem, what changed and the business effect behind the finished experience.</p></div><div class="impact-grid"><?php $i=1; foreach($featured as $p):?><a class="impact-card <?=($i===1?'wide ':'')?>reveal" href="/work/<?=htmlspecialchars($p[0])?>"><div class="impact-media project-shot"><img src="<?=htmlspecialchars(ferrn_shot($p[4]))?>" alt="<?=htmlspecialchars($p[1])?> website screenshot" loading="lazy"><span class="impact-index"><?=str_pad((string)$i,2,'0',STR_PAD_LEFT)?> · <?=htmlspecialchars($p[3])?></span><span class="impact-open"><i data-lucide="arrow-up-right"></i></span></div><div class="impact-body"><div class="impact-meta"><h3 class="impact-title"><?=htmlspecialchars($p[1])?></h3><span class="impact-type"><?=htmlspecialchars($p[2])?></span></div><p class="impact-desc"><?=htmlspecialchars($p[5])?></p><div class="impact-result"><strong><?=($p[0]==='relay'?'Operational effect':'Business effect')?></strong><span><?=htmlspecialchars($p[6])?></span></div></div></a><?php $i++; endforeach;?></div><div style="margin-top:30px;display:flex;justify-content:flex-end" class="reveal"><a class="btn btn-ghost" href="/work/">View all case studies <i data-lucide="arrow-right"></i></a></div></div></section>

<section class="section" id="services"><div class="container services-layout"><div class="sticky reveal"><span class="eyebrow">What we build</span><h2 class="h2">One team across strategy, design and build.</h2><p class="lead" style="margin-top:26px">You should not need three vendors to turn one business problem into a working digital product.</p></div><div class="service-list reveal"><article class="service-row"><span class="service-num">01</span><h3>Conversion-focused websites</h3><p>Positioning, information architecture, UI design and frontend development for businesses whose online presence needs to sell the same level of credibility they deliver offline.</p><span class="icon-wrap"><i data-lucide="monitor-up"></i></span></article><article class="service-row"><span class="service-num">02</span><h3>Custom web applications</h3><p>Dashboards, portals, operational tools and workflow systems designed around the process your team actually runs—not the feature list of a generic SaaS product.</p><span class="icon-wrap"><i data-lucide="panels-top-left"></i></span></article><article class="service-row"><span class="service-num">03</span><h3>UI/UX & product design</h3><p>User journeys, product structure, prototyping and interface systems for software that needs to be understandable before it can be useful.</p><span class="icon-wrap"><i data-lucide="figma"></i></span></article><article class="service-row"><span class="service-num">04</span><h3>AI & automation</h3><p>Practical automation layers and AI-assisted workflows where they remove repetitive work, improve response time or make an existing system more valuable.</p><span class="icon-wrap"><i data-lucide="sparkles"></i></span></article></div></div></section>

<section class="section"><div class="container"><div class="section-head reveal"><div><span class="eyebrow">How we work</span><h2 class="h2">Fast enough to move. Structured enough to trust.</h2></div><p class="lead">A clear sequence keeps speed from turning into chaos.</p></div><div class="process-grid reveal"><?php $steps=[['01 / DISCOVER','Understand','We find the commercial problem, users, constraints and what success should actually mean.'],['02 / DEFINE','Scope','We turn the problem into the smallest useful product, site structure or system roadmap.'],['03 / DESIGN','Shape','We make the experience visible early so important decisions are reviewed before build.'],['04 / BUILD','Develop','Responsive frontend, backend logic, integrations and content systems are implemented and tested.'],['05 / LAUNCH','Ship','We deploy, hand over, support and improve the product using real usage and business feedback.']]; foreach($steps as $s):?><article class="step"><span><?=htmlspecialchars($s[0])?></span><div><h3><?=htmlspecialchars($s[1])?></h3><p><?=htmlspecialchars($s[2])?></p></div></article><?php endforeach;?></div></div></section>

<section class="section" id="about"><div class="container"><div class="section-head reveal"><div><span class="eyebrow">About Ferrn Digital Agency</span><h2 class="h2">Focused enough to care. Capable enough to ship.</h2></div><p class="lead">Ferrn Digital Agency combines business thinking, interface design and engineering to help companies launch digital products that solve a real problem.</p></div><div class="impact-grid"><article class="impact-card reveal" style="grid-column:span 7;min-height:430px"><div class="impact-body" style="padding:clamp(28px,4vw,52px)"><span class="kicker">The operating principle</span><h3 class="impact-title" style="font-size:clamp(38px,5vw,72px)">Make money. Save time. Solve something worth solving.</h3><p class="impact-desc">A website should improve trust, positioning or demand. A web application should remove friction, create visibility or unlock a workflow that matters.</p></div></article><article class="impact-card reveal" style="grid-column:span 5;min-height:430px;background:var(--accent);color:var(--contrast);border-color:transparent"><div class="impact-body" style="padding:clamp(28px,4vw,52px)"><span class="kicker">Working globally</span><h3 class="impact-title" style="font-size:clamp(36px,5vw,70px)">We build what’s next.</h3><p class="impact-desc" style="color:inherit">From company websites to product platforms and internal systems, Ferrn Digital Agency works with founders and teams that need sharp execution without agency theatre.</p></div></article></div></div></section>

<section class="section" id="insights"><div class="container"><div class="section-head reveal"><div><span class="eyebrow">Insights</span><h2 class="h2">Useful thinking, not content for content’s sake.</h2></div><p class="lead">Notes on websites, product decisions, custom software and operational systems.</p></div><div class="insights-grid" id="insightsGrid"><a class="article-card" href="/insights/"><div class="article-meta"><span>Loading</span><span>Ferrn</span></div><h3>Opening the latest notes…</h3><p>The CMS feeds published articles into this section automatically.</p><div class="article-link"><span>Browse insights</span><i data-lucide="arrow-up-right"></i></div></a></div><div style="margin-top:26px;display:flex;justify-content:flex-end"><a class="btn btn-ghost" href="/insights/">All insights <i data-lucide="arrow-right"></i></a></div></div></section>

<section class="section" id="contact"><div class="container"><div class="contact-wrap"><div class="contact-panel reveal"><span class="eyebrow">Start a project</span><h2>Tell us what needs to work better.</h2><p>You do not need a perfect brief. Tell us what the business is trying to improve, launch or automate. We will tell you what we think should be built and the clearest next step.</p><a class="contact-email" href="mailto:info@ferrnagency.com">info@ferrnagency.com</a></div><form class="contact-form reveal" id="contactForm"><div class="hp"><label>Website<input name="website" tabindex="-1" autocomplete="off"></label></div><div class="form-grid"><div class="field"><label for="name">Your name *</label><input id="name" name="name" required autocomplete="name"></div><div class="field"><label for="email">Work email *</label><input id="email" name="email" type="email" required autocomplete="email"></div><div class="field"><label for="company">Company</label><input id="company" name="company" autocomplete="organization"></div><div class="field"><label for="project">What do you need?</label><select id="project" name="project"><option>Website</option><option>Web application</option><option>Portal / dashboard</option><option>UI/UX product design</option><option>AI / automation</option><option>Not sure yet</option></select></div><div class="field"><label for="budget">Approximate budget</label><select id="budget" name="budget"><option value="">Prefer not to say</option><option>$3k–$5k</option><option>$5k–$15k</option><option>$15k–$30k</option><option>$30k+</option></select></div><div class="field"><label for="timeline">Timeline</label><select id="timeline" name="timeline"><option>As soon as possible</option><option>Within 1 month</option><option>1–3 months</option><option>Exploring</option></select></div><div class="field full"><label for="message">What are you trying to improve? *</label><textarea id="message" name="message" required placeholder="A few sentences is enough…"></textarea></div></div><div class="form-footer"><p class="form-note">Your enquiry is saved privately in the Ferrn Digital Agency dashboard so the team can follow up.</p><button class="btn btn-primary" type="submit">Send enquiry <i data-lucide="send"></i></button></div><div class="form-status" id="formStatus" aria-live="polite"></div></form></div></div></section>
</main><?php include __DIR__.'/lib/footer.php'; ?></body></html>
