<?php
declare(strict_types=1);
require_once __DIR__.'/lib/projects.php';
$projects=ferrn_projects();
$pageTitle='Ferrn Digital Agency — Websites, Web Apps & AI Automation for Growth';
$pageDescription='Ferrn Digital Agency designs and builds conversion-focused websites, custom web applications and AI automation systems that help businesses win trust, generate opportunities and operate with less manual work.';
$canonical='https://www.ferrnagency.com/';
$schema=['@context'=>'https://schema.org','@graph'=>[
 ['@type'=>'Organization','@id'=>'https://www.ferrnagency.com/#org','name'=>'Ferrn Digital Agency','url'=>'https://www.ferrnagency.com/','email'=>'info@ferrnagency.com','logo'=>'https://www.ferrnagency.com/assets/ferrn-mark.svg','description'=>$pageDescription,'areaServed'=>'Worldwide','sameAs'=>['https://www.instagram.com/ferrn.agency/','https://x.com/ferrn_agency','https://www.linkedin.com/company/109135329/','https://www.tiktok.com/@ferrnagency']],
 ['@type'=>'WebSite','@id'=>'https://www.ferrnagency.com/#website','url'=>'https://www.ferrnagency.com/','name'=>'Ferrn Digital Agency','publisher'=>['@id'=>'https://www.ferrnagency.com/#org']],
 ['@type'=>'Service','name'=>'Website design, web application development and AI automation','provider'=>['@id'=>'https://www.ferrnagency.com/#org'],'areaServed'=>'Worldwide','serviceType'=>['Web Design','Web Development','Custom Web Applications','Client Portals','Dashboards','AI Automation']]
]];
$featured=array_filter($projects,fn($p)=>!empty($p['featured']));
$industries=[];foreach($projects as $p){if(!empty($p['industry']))$industries[$p['industry']]=true;}
$categories=[];foreach($projects as $p){if(!empty($p['category']))$categories[$p['category']]=true;}
$testimonials=[
 ['Vanessa','CEO, Bagzilla','https://res.cloudinary.com/dyizdpyem/image/upload/v1774525428/WhatsApp_Image_2026-03-26_at_11.38.36_y99rhu.jpg',"Working with Ferrn completely shifted our trajectory. They didn't just design a website, they built a machine that actually converts our audience."],
 ['Chisom','CEO, Hush D','https://res.cloudinary.com/dyizdpyem/image/upload/v1774525428/Screenshot_2026-03-25_at_10.17.36_PM_u3t6hu.png','The attention to detail is insane. We handed them a broken brand, and they handed us back a masterpiece. I cannot recommend them enough.'],
 ['John Sax','CEO, Jstar Films','https://res.cloudinary.com/dyizdpyem/image/upload/v1774525428/me_gm1itv.jpg','Fast, ruthless, and incredibly talented. They cut out all the agency fluff and just delivered pure, high-end results on time.']
];
?><!doctype html><html lang="en" data-theme="dark"><head><?php include __DIR__.'/lib/head.php'; ?></head><body>
<?php include __DIR__.'/lib/nav.php'; ?>
<main>
<section class="hero" id="top"><div class="container hero-inner"><div class="hero-topline reveal"><div class="availability global-pill"><span class="availability-dot"></span>Working globally</div></div><h1 class="reveal">Websites, web apps and AI systems built to <span class="accent">move the business forward.</span></h1><div class="hero-bottom reveal"><p class="hero-copy">Ferrn Digital Agency turns business problems into conversion-focused websites, custom web applications and AI automation. We help companies look more credible, create better customer journeys and replace manual processes that slow growth.</p><div class="hero-actions"><a class="btn btn-primary" href="#contact">Start a project <i data-lucide="arrow-up-right"></i></a><a class="btn btn-ghost" href="/work/">See the work <i data-lucide="arrow-right"></i></a></div></div><div class="hero-proof reveal"><p>Strategy · UI/UX · Development · Automation</p><div class="proof-chips"><span class="proof-chip">High-converting websites</span><span class="proof-chip">Custom web apps</span><span class="proof-chip">Client portals</span><span class="proof-chip">Dashboards</span><span class="proof-chip">AI workflows</span></div></div></div></section>

<section class="client-rail" aria-label="Clients"><div class="marquee"><?php $logos=[['clientLogo1.svg','Gromzia'],['clientLogo2.svg','Synergix Africa'],['clientLogo3.svg','M-P Infrastructure'],['clientLogo5.svg','Aroda'],['clientLogo6.svg','Outbox Experience'],['clientLogo7.svg','Knomi'],['clientLogo12.svg','Padher']]; foreach(array_merge($logos,$logos) as $l):?><div class="client-logo"><img src="https://raw.githubusercontent.com/FERRN-AGENCY/ferrn-website/main/fern/src/assets/<?=htmlspecialchars($l[0])?>" alt="<?=htmlspecialchars($l[1])?> logo"></div><?php endforeach;?></div></section>

<section class="section metrics-section"><div class="container"><div class="metrics-grid reveal"><article><strong><?=count($projects)?>+</strong><span>selected digital builds</span></article><article><strong><?=count($industries)?>+</strong><span>industries represented</span></article><article><strong><?=count($categories)?></strong><span>core build categories</span></article><article><strong>1</strong><span>team from strategy to launch</span></article></div></div></section>

<section class="section" id="impact"><div class="container"><div class="section-head reveal"><div><span class="eyebrow">Selected impact</span><h2 class="h2">The interface is visible. The business effect is the point.</h2></div><p class="lead">Explore real client work across websites, web applications and AI automation. Every case study explains the business problem, what Ferrn changed and why the finished experience matters.</p></div>
<div class="impact-tabs reveal" role="tablist" aria-label="Filter selected work"><button class="impact-tab active" data-project-filter="website" type="button">Websites</button><button class="impact-tab" data-project-filter="webapp" type="button">Web apps</button><button class="impact-tab" data-project-filter="ai" type="button">AI automations</button></div>
<div class="impact-grid" id="impactGrid"><?php $i=1;foreach($featured as $slug=>$p):$cat=$p['category']??'website';?><a class="impact-card reveal" data-project-category="<?=htmlspecialchars($cat)?>" href="/work/<?=htmlspecialchars($slug)?>"><div class="impact-media project-shot"><img src="<?=htmlspecialchars(ferrn_screenshot_url($p['live']))?>" alt="Screenshot of <?=htmlspecialchars($p['title'])?>" loading="lazy"><span class="impact-index"><?=str_pad((string)$i,2,'0',STR_PAD_LEFT)?> · <?=htmlspecialchars($p['type'])?></span><span class="impact-open"><i data-lucide="arrow-up-right"></i></span></div><div class="impact-body"><div class="impact-meta"><h3 class="impact-title"><?=htmlspecialchars($p['title'])?></h3><span class="impact-type"><?=htmlspecialchars($p['industry']??$p['type'])?></span></div><p class="impact-desc"><?=htmlspecialchars($p['summary'])?></p><div class="impact-result"><strong><?=($cat==='webapp'?'Operational effect':($cat==='ai'?'User effect':'Business effect'))?></strong><span><?=htmlspecialchars($p['impact'])?></span></div></div></a><?php $i++;endforeach;?></div><div class="reveal section-action"><a class="btn btn-ghost" href="/work/">View all case studies <i data-lucide="arrow-right"></i></a></div></div></section>

<section class="section" id="services"><div class="container services-layout"><div class="sticky reveal"><span class="eyebrow">What we build</span><h2 class="h2">Choose the product that solves the actual business problem.</h2><p class="lead" style="margin-top:26px">You do not need “more digital.” You need the right system for the constraint in front of you.</p></div><div class="service-list reveal"><article class="service-row"><span class="service-num">01</span><h3>Conversion-focused websites</h3><p>For businesses that need stronger positioning, more trust and a clearer path from first visit to qualified enquiry. We combine strategy, information architecture, UI design, development and SEO-ready structure.</p><span class="icon-wrap"><i data-lucide="monitor-up"></i></span></article><article class="service-row"><span class="service-num">02</span><h3>Custom web applications</h3><p>For teams losing time to spreadsheets, disconnected tools and manual handoffs. We build portals, dashboards and workflow systems around the way the business actually operates.</p><span class="icon-wrap"><i data-lucide="panels-top-left"></i></span></article><article class="service-row"><span class="service-num">03</span><h3>AI automation</h3><p>For processes where conversational interfaces, document intelligence or AI-assisted workflows can reduce repetitive work and make information easier to access.</p><span class="icon-wrap"><i data-lucide="sparkles"></i></span></article></div></div></section>

<section class="section"><div class="container"><div class="section-head reveal"><div><span class="eyebrow">Client feedback</span><h2 class="h2">Good work should make the next conversation easier.</h2></div><p class="lead">Feedback from clients who trusted Ferrn with their digital experience, product or brand.</p></div><div class="testimonial-grid"><?php foreach($testimonials as $t):?><article class="testimonial-card reveal"><p class="testimonial-quote">“<?=htmlspecialchars($t[3])?>”</p><div class="testimonial-person"><img src="<?=htmlspecialchars($t[2])?>" alt="<?=htmlspecialchars($t[0])?>" loading="lazy"><div><strong><?=htmlspecialchars($t[0])?></strong><span><?=htmlspecialchars($t[1])?></span></div></div></article><?php endforeach;?></div></div></section>

<section class="section"><div class="container"><div class="section-head reveal"><div><span class="eyebrow">How we work</span><h2 class="h2">Fast enough to move. Structured enough to trust.</h2></div><p class="lead">A clear delivery system keeps speed from turning into chaos.</p></div><div class="process-grid reveal"><?php $steps=[['01 / DISCOVER','Understand','We find the commercial problem, users, constraints and what success should mean.'],['02 / DEFINE','Scope','We turn the problem into a focused website, application or automation roadmap.'],['03 / DESIGN','Shape','We make the experience visible early so important decisions happen before expensive build work.'],['04 / BUILD','Develop','Frontend, backend, integrations and content systems are implemented and tested.'],['05 / LAUNCH','Ship','We deploy, hand over, support and improve using real business feedback.']];foreach($steps as $s):?><article class="step"><span><?=htmlspecialchars($s[0])?></span><div><h3><?=htmlspecialchars($s[1])?></h3><p><?=htmlspecialchars($s[2])?></p></div></article><?php endforeach;?></div></div></section>

<section class="section" id="about"><div class="container"><div class="section-head reveal"><div><span class="eyebrow">About Ferrn Digital Agency</span><h2 class="h2">A focused digital product partner, not another layer of agency overhead.</h2></div><p class="lead">Ferrn combines business strategy, UI/UX design and engineering so companies can move from a problem to a working digital product with one accountable team.</p></div><div class="impact-grid"><article class="impact-card reveal about-card-main"><div class="impact-body"><span class="kicker">Our operating principle</span><h3 class="impact-title about-statement">Make money. Save time. Solve something worth solving.</h3><p class="impact-desc">A website should strengthen trust and demand. A web application should create visibility or remove operational friction. AI should make a useful process faster or easier—not exist because it is fashionable.</p></div></article><article class="impact-card reveal about-card-accent"><div class="impact-body"><span class="kicker global-black-label">Working globally</span><h3 class="impact-title about-statement">We build what’s next.</h3><p class="impact-desc">From company websites to customer portals, internal systems and AI experiences, we help teams turn digital ideas into products that can actually be used.</p></div></article></div></div></section>

<section class="section" id="insights"><div class="container"><div class="section-head reveal"><div><span class="eyebrow">Insights</span><h2 class="h2">Useful thinking for better digital decisions.</h2></div><p class="lead">Practical guidance on conversion-focused websites, custom software, product strategy and AI automation—written for teams deciding what to build next.</p></div><div class="insights-grid" id="insightsGrid"><a class="article-card" href="/insights/"><div class="article-meta"><span>Loading</span><span>Ferrn</span></div><h3>Opening the latest notes…</h3><p>Published insights appear here automatically.</p><div class="article-link"><span>Browse insights</span><i data-lucide="arrow-up-right"></i></div></a></div><div class="section-action"><a class="btn btn-ghost" href="/insights/">All insights <i data-lucide="arrow-right"></i></a></div></div></section>

<section class="section" id="contact"><div class="container"><div class="contact-wrap"><div class="contact-panel reveal"><span class="eyebrow">Start a project</span><h2>Tell us the problem. We’ll help define what should be built.</h2><p>You do not need a perfect technical brief. Tell us what is costing the business opportunities, time or visibility. We will help identify whether the answer is a website, web application, portal, dashboard or AI workflow.</p><a class="contact-email" href="mailto:info@ferrnagency.com">info@ferrnagency.com</a></div><form class="contact-form reveal" id="contactForm"><div class="hp"><label>Website<input name="website" tabindex="-1" autocomplete="off"></label></div><div class="form-grid"><div class="field"><label for="name">Your name *</label><input id="name" name="name" required autocomplete="name"></div><div class="field"><label for="email">Work email *</label><input id="email" name="email" type="email" required autocomplete="email"></div><div class="field"><label for="company">Company</label><input id="company" name="company" autocomplete="organization"></div><div class="field"><label for="project">What do you need?</label><select id="project" name="project"><option>Website</option><option>Web application</option><option>Portal / dashboard</option><option>AI / automation</option><option>Not sure yet</option></select></div><div class="field"><label for="budget">Approximate budget</label><select id="budget" name="budget"><option value="">Prefer not to say</option><option>$3k–$5k</option><option>$5k–$15k</option><option>$15k–$30k</option><option>$30k+</option></select></div><div class="field"><label for="timeline">Timeline</label><select id="timeline" name="timeline"><option>As soon as possible</option><option>Within 1 month</option><option>1–3 months</option><option>Exploring</option></select></div><div class="field full"><label for="message">What are you trying to improve? *</label><textarea id="message" name="message" required placeholder="What is happening today, and what would you like to work better?"></textarea></div></div><div class="form-footer"><p class="form-note">Your enquiry goes directly into our private project dashboard.</p><button class="btn btn-primary" type="submit">Send enquiry <i data-lucide="send"></i></button></div><div class="form-status" id="formStatus" aria-live="polite"></div></form></div></div></section>
</main><?php include __DIR__.'/lib/footer.php'; ?></body></html>
