<?php
declare(strict_types=1);
/* Editable starter material. Policies describing unverified organisational processes stay unpublished until Ferrn approves them. */
function ferrn_policy_drafts(): array {
 $base=[
 ['Privacy Policy','How Ferrn handles information submitted through its website.',
 '<h2>Scope</h2><p>This notice describes personal information submitted through the Ferrn Agency website and its current website features. For privacy questions, email info@ferrnagency.com.</p><h2>Information we collect</h2><p>If you contact us, submit a project enquiry or send an RFP, the information you choose to provide may include your name, work email, company, contact details, project description and uploaded documents. Newsletter forms collect your email address and optional name. Our website assistant processes messages you choose to submit using approved Ferrn information. Ferrn also keeps a private record of up to 2,000 recent chatbot questions (each truncated to 450 characters) and their submission times and page paths to review common enquiries and improve answers. Please do not share medical details, passwords, payment credentials or other sensitive information through the assistant. Speech-to-text and spoken replies, where supported by your browser, use browser speech features.</p><h2>How the information is used</h2><p>Information from forms is used to respond to enquiries, review project requirements and manage the related communication. Newsletter information is used to maintain the subscription list. If you accept optional analytics, the site records page visits and interactions such as link and button clicks, along with approximate on-page locations for an aggregate click heatmap. We do not deliberately include form-field contents in click events.</p><h2>Storage and service providers</h2><p>Submitted website records are maintained in private server-side storage. Website hosting and tools used to deliver the services necessarily process some information. If you use the chatbot, your submitted message and relevant approved Ferrn knowledge are sent to its configured AI service to generate a response. Before sharing sensitive documents, contact Ferrn to discuss appropriate handling.</p><h2>Cookies and analytics choices</h2><p>Optional analytics require affirmative acceptance through the website notice. Your choice is saved in browser storage and can be revisited through Cookie preferences in the footer.</p><h2>Questions and requests</h2><p>To ask what information you supplied or request a correction or deletion, contact info@ferrnagency.com. Requests are reviewed subject to applicable requirements and legitimate record-keeping needs.</p>',true],
 ['Cookie Policy','Browser storage and your analytics preferences on the Ferrn website.',
 '<h2>Essential browser storage</h2><p>The website uses browser storage for presentation preferences and, where relevant, temporary interface state. A session identifier is used for optional analytics events only after you opt in.</p><h2>Optional first-party analytics</h2><p>Accepting analytics enables first-party tracking of page views and website interactions, including approximate positions of clicks for aggregate website heatmaps. Choosing Necessary only prevents these optional analytics submissions. Closing the notice without choosing is not treated as consent.</p><h2>Update your choice</h2><p>Open Cookie preferences in the website footer to review your choice. To withdraw an earlier decision, clear the saved Ferrn website preferences in your browser; the banner will appear again. Contact info@ferrnagency.com with related questions.</p>',true],
 ['Terms of Use','Information about using the Ferrn Agency public website.',
 '<h2>General information</h2><p>Website material describes Ferrn Agency services and selected work for general information. Individual projects require agreed scope, terms and commercial documentation. A website enquiry or RFP submission does not itself establish a contract.</p><h2>Permitted use</h2><p>Do not misuse the website, attempt unauthorised access, submit malicious material or falsely represent another person or organisation through its forms.</p><h2>Information and availability</h2><p>Information may change as services and projects evolve. Use the official contact details to confirm project requirements, proposals and current availability.</p><h2>Questions</h2><p>For questions about the website, contact info@ferrnagency.com.</p>',true],
 ['Data Protection Policy','Internal data-handling policy template for review before publication.',
 '<h2>Purpose</h2><p>This draft describes proposed principles for handling information across Ferrn projects. Ferrn management must confirm applicable laws, processing purposes, lawful bases, retention schedules and project-specific controller/processor responsibilities before publishing.</p><h2>Proposed principles</h2><ul><li>Collect information needed for an agreed purpose only.</li><li>Restrict access to team members with a documented business need.</li><li>Use approved service providers and assess relevant data-processing requirements.</li><li>Document deletion, correction, incident response and retention procedures for each engagement.</li></ul><h2>Review required</h2><p>This is an editable internal template, not a representation of existing certification or regulatory approval.</p>',false],
 ['Information Security Policy','Internal security policy template for management approval.',
 '<h2>Scope</h2><p>Applies to proposed controls for company-managed systems and client engagements once adopted. Define system owners, asset inventory and the applicable obligations for every engagement.</p><h2>Proposed controls</h2><ul><li>Role-based access and least privilege.</li><li>Controlled credential and secret management.</li><li>Separate development and production environments where appropriate.</li><li>Documented backups, reviews and change control.</li><li>Project-appropriate vulnerability reporting and incident escalation.</li></ul><h2>Review required</h2><p>Management must validate implementation, responsible owners and any commitments before publication.</p>',false],
 ['Acceptable Use Policy','Internal template defining acceptable use of company systems.',
 '<h2>Purpose</h2><p>To define permitted use of Ferrn accounts, devices, development resources, client data and collaboration systems.</p><h2>Proposed requirements</h2><ul><li>Use business systems only with authorisation.</li><li>Do not share account credentials or publish secrets in repositories.</li><li>Respect client confidentiality and approved data-handling instructions.</li><li>Report suspected access or security incidents promptly.</li></ul><h2>Review required</h2><p>Management should assign ownership, define enforcement and approve this policy before publication.</p>',false],
 ['Accessibility Statement','Accessibility commitment template requiring verification.',
 '<h2>Our approach</h2><p>Ferrn seeks to design clear, usable digital experiences, including responsive layouts and meaningful interaction labels.</p><h2>Feedback</h2><p>If a page or document is difficult to use, contact info@ferrnagency.com and describe the page and the difficulty encountered.</p><h2>Verification required</h2><p>Do not claim compliance with a specific WCAG level until an accessibility audit supports that statement.</p>',false],
 ['Modern Slavery Statement','Template requiring confirmation of legal applicability and supplier practices.',
 '<h2>Purpose</h2><p>Ferrn intends to work respectfully and responsibly with its team and suppliers.</p><h2>Before publication</h2><p>Management must confirm legal applicability, the reporting period, supplier oversight, grievance channels and approval before adopting this statement.</p>',false],
 ['Anti-Bribery / Anti-Corruption Policy','Draft expectations for ethical engagements and procurement.',
 '<h2>Proposed principles</h2><p>Staff and partners should not offer or accept improper payments, kickbacks or incentives to obtain business or influence procurement decisions.</p><h2>Controls to confirm</h2><p>Before publication, management must specify approval thresholds, gifts guidance, reporting channels, relevant training and any legally required reporting processes.</p>',false],
 ['Conflict of Interest Policy','Draft process for disclosing competing interests.',
 '<h2>Proposed principles</h2><p>Team members and contractors should disclose personal, financial or business relationships that may conflict with responsibilities to Ferrn or its clients.</p><h2>Review required</h2><p>Management must set the disclosure process, review authority and record-handling arrangements before adopting this policy.</p>',false],
 ['Code of Conduct','Draft behavioural expectations for the Ferrn team and partners.',
 '<h2>Professional practice</h2><p>Ferrn expects thoughtful collaboration, accurate project reporting, respect for clients and colleagues, and responsible handling of confidential materials.</p><h2>Before publication</h2><p>Management should approve reporting routes, investigation processes and scope of application before adopting this draft code.</p>',false]
 ];
 $out=[];
 foreach($base as [$title,$summary,$html,$approved]){
  $slug=ferrn_slugify($title);
  $out[]=['id'=>$slug,'slug'=>$slug,'title'=>$title,'summary'=>$summary,'content'=>$html,'published'=>$approved,'updated_at'=>'2026-09-30T00:00:00+01:00'];
 }
 return $out;
}
