<?php
declare(strict_types=1);
require_once __DIR__.'/../lib/platform.php';
$settings=ferrn_settings();
$company=$settings['company']; $contact=$settings['contact'];
$certs=ferrn_collection('certifications'); $policies=ferrn_collection('policies',ferrn_default_policies());
$pageTitle='Procurement & Vendor Information — Ferrn Agency';
$pageDescription='Ferrn Agency procurement, vendor, capability, compliance and RFP information for organisations evaluating Ferrn as a digital delivery partner.';
$canonical='https://www.ferrnagency.com/procurement/';
?><!doctype html><html lang="en" data-theme="dark"><head><?php include __DIR__.'/../lib/head.php'; ?></head><body><?php include __DIR__.'/../lib/nav.php'; ?>
<main><section class="section procurement-hero"><div class="container"><span class="eyebrow">Work with Ferrn</span><h1 class="h1">Procurement-ready information for serious digital projects.</h1><p class="lead">A single place for vendor details, capabilities, compliance documents and formal project enquiries.</p><div class="hero-actions"><a class="btn btn-primary" href="/rfp/">Submit an RFP <i data-lucide="arrow-up-right"></i></a><?php if(!empty($company['company_profile_url'])):?><a class="btn btn-ghost" href="<?=htmlspecialchars($company['company_profile_url'])?>" download>Download company profile <i data-lucide="download"></i></a><?php endif;?><?php if(!empty($company['capability_statement_url'])):?><a class="btn btn-ghost" href="<?=htmlspecialchars($company['capability_statement_url'])?>" target="_blank" rel="noopener">Capability statement</a><?php endif;?></div></div></section>
<section class="section"><div class="container"><div class="section-head"><div><span class="eyebrow">Vendor information</span><h2 class="h2">Company details.</h2></div></div><div class="procurement-grid">
<?php $rows=[
['Registered company name',$settings['brand']['legal_name']],['Registration jurisdiction',$company['registration_jurisdiction']],['Registration number',$company['registration_number']],['Registered business address',$contact['address']],['Year established',$company['year_established']],['Ownership structure',$company['ownership_structure']],['Tax information',$company['tax_information']],['Geographic coverage',$company['geographic_coverage']],['Procurement contact',$company['procurement_contact']],['Official business email',$contact['email']]
]; foreach($rows as $r): if(trim((string)$r[1])==='') continue;?><article class="procurement-item"><span><?=htmlspecialchars($r[0])?></span><strong><?=htmlspecialchars((string)$r[1])?></strong></article><?php endforeach;?></div></div></section>
<section class="section"><div class="container"><div class="section-head"><div><span class="eyebrow">Capabilities</span><h2 class="h2">What Ferrn can deliver.</h2></div><p class="lead">Digital strategy, product design and engineering delivered as one accountable capability.</p></div><div class="service-list"><article class="service-row"><span class="service-num">01</span><h3>Digital experience & campaign websites</h3><p>Conversion-focused corporate websites, campaign platforms, landing pages and interactive brand experiences.</p></article><article class="service-row"><span class="service-num">02</span><h3>Custom web applications</h3><p>Portals, workflow systems, dashboards, internal tools and customer-facing applications.</p></article><article class="service-row"><span class="service-num">03</span><h3>AI systems & automation</h3><p>AI-assisted workflows, knowledge experiences, chat interfaces and task automation tied to measurable business outcomes.</p></article></div></div></section>
<section class="section"><div class="container"><div class="section-head"><div><span class="eyebrow">Compliance & recognition</span><h2 class="h2">Documents and credentials.</h2></div></div><div class="credential-grid"><?php foreach($certs as $c):?><article class="credential-card"><i data-lucide="badge-check"></i><h3><?=htmlspecialchars($c['name']??'Certification')?></h3><p><?=htmlspecialchars($c['issuer']??'')?></p></article><?php endforeach;?><?php foreach($policies as $p): if(empty($p['published'])) continue;?><a class="credential-card" href="/policies/<?=htmlspecialchars($p['slug'])?>/"><i data-lucide="file-check-2"></i><h3><?=htmlspecialchars($p['title'])?></h3><p><?=htmlspecialchars($p['summary']??'Read policy')?></p></a><?php endforeach;?></div></div></section>
<section class="section"><div class="container"><div class="contact-wrap"><div class="contact-panel"><span class="eyebrow">Formal procurement</span><h2>Have an RFP, tender or vendor questionnaire?</h2><p>Send the project details and supporting documents through Ferrn's dedicated RFP intake.</p></div><div class="proposal-cta"><a class="btn btn-primary" href="/rfp/">Open RFP form <i data-lucide="arrow-up-right"></i></a><?php if(!empty($company['company_profile_url'])):?><a class="btn btn-ghost" href="<?=htmlspecialchars($company['company_profile_url'])?>" target="_blank" rel="noopener">Company profile</a><?php endif;?></div></div></div></section></main><?php include __DIR__.'/../lib/footer.php'; ?></body></html>