<?php
declare(strict_types=1);
require_once __DIR__.'/../lib/platform.php';
$pageTitle='Submit an RFP — Ferrn Agency';
$pageDescription='Send Ferrn Agency a formal RFP, tender or digital project brief with procurement deadlines and supporting documents.';
$canonical='https://www.ferrnagency.com/rfp/';
?><!doctype html><html lang="en" data-theme="dark"><head><?php include __DIR__.'/../lib/head.php'; ?></head><body><?php include __DIR__.'/../lib/nav.php'; ?><main><section class="section"><div class="container"><span class="eyebrow">RFP / Tender intake</span><h1 class="h1">Send Ferrn the complete brief.</h1><p class="lead">For organisations evaluating Ferrn for a website, web application, AI system, campaign platform or digital transformation engagement.</p><form class="contact-form rfp-form" id="rfpForm" enctype="multipart/form-data"><div class="form-grid">
<?php $fields=[['company','Company *','text',1],['name','Name *','text',1],['email','Work email *','email',1],['phone','Phone','tel',0],['country','Country *','text',1],['project_type','Project type *','text',1],['budget','Budget range','text',0],['launch_date','Expected launch date','date',0],['procurement_deadline','Procurement deadline','date',0],['rfp_reference','RFP reference','text',0]]; foreach($fields as $f):?><div class="field"><label for="<?=$f[0]?>"><?=$f[1]?></label><input id="<?=$f[0]?>" name="<?=$f[0]?>" type="<?=$f[2]?>" <?=$f[3]?'required':''?>></div><?php endforeach;?>
<div class="field full"><label for="services">Required services *</label><input id="services" name="services" required placeholder="e.g. product strategy, UI/UX, frontend, backend, AI integration"></div>
<div class="field full"><label for="description">Project description *</label><textarea id="description" name="description" required></textarea></div>
<div class="field"><label for="rfp_file">Upload RFP</label><input id="rfp_file" name="rfp_file" type="file" accept=".pdf,.doc,.docx,.txt"></div>
<div class="field"><label for="supporting_file">Supporting document</label><input id="supporting_file" name="supporting_file" type="file" accept=".pdf,.doc,.docx,.xls,.xlsx,.csv,.ppt,.pptx,.zip"></div>
</div><div class="form-footer"><p class="form-note">Files are stored privately outside the public website directory.</p><button class="btn btn-primary" type="submit">Submit RFP <i data-lucide="send"></i></button></div><div class="form-status" id="rfpStatus" aria-live="polite"></div></form></div></section></main><?php include __DIR__.'/../lib/footer.php'; ?><script>document.querySelector('#rfpForm')?.addEventListener('submit',async e=>{e.preventDefault();const f=e.currentTarget,s=document.querySelector('#rfpStatus'),b=f.querySelector('button[type=submit]');b.disabled=true;s.textContent='Submitting…';try{const r=await fetch('/api/rfp.php',{method:'POST',body:new FormData(f),headers:{'X-Requested-With':'XMLHttpRequest'}});const d=await r.json();if(!r.ok||!d.ok)throw new Error(d.message||'Could not submit RFP.');f.reset();s.textContent='RFP received. Ferrn will review the submission.';}catch(err){s.textContent=err.message||'Submission failed.';}finally{b.disabled=false;}});</script></body></html>